version: '3.8'

services:
  web:
    build: .
    container_name: ${COMPOSE_PROJECT_NAME:-aviationwx}-web
    restart: always
    ports:
      - "127.0.0.1:${APP_PORT:-8080}:80"  # Bind to localhost only, Nginx handles external
    volumes:
      # Mount airports.json from user home directory (deployed by secrets repo GitHub Actions)
      - /home/aviationwx/airports.json:/var/www/html/airports.json:ro
      - ./cache:/var/www/html/cache
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - DOMAIN=${DOMAIN:-aviationwx.org}
      - CONFIG_PATH=/var/www/html/airports.json
      - WEBCAM_REFRESH_DEFAULT=${WEBCAM_REFRESH_DEFAULT:-60}
      - WEATHER_REFRESH_DEFAULT=${WEATHER_REFRESH_DEFAULT:-60}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: aviationwx-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # SSL certificates
    depends_on:
      - web
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

