# Fail2ban filter for ProFTPD authentication failures.

[Definition]

failregex = ^.*\([^[]+\[<HOST>\]\): USER .* \(Login failed\).*$
            ^.*\([^[]+\[<HOST>\]\): USER .*no such user found.*$

ignoreregex =
