# Fail2ban filter for ProFTPD authentication failures.

[Definition]

failregex = ^.*\([a-zA-Z0-9._/-]+\): FTP login failed for (?:user|anonymous) '.*' from [^\[]+\[<HOST>\].*$
            ^.*\([a-zA-Z0-9._/-]+\): no such user '.*' from [^\[]+\[<HOST>\].*$

ignoreregex =
