#!/bin/bash
# Configure and start ProFTPD for push camera uploads.
# Sourced or executed from docker-entrypoint.sh with network_ports env already set.

set -euo pipefail

PROFTPD_CONF="${PROFTPD_CONF:-/etc/proftpd/proftpd.conf}"
CONFIG_FILE="${CONFIG_FILE:-/var/www/html/config/airports.json}"
FTP_CONTROL_PORT="${FTP_CONTROL_PORT:-2121}"
FTP_PASSIVE_MIN="${FTP_PASSIVE_MIN:-50000}"
FTP_PASSIVE_MAX="${FTP_PASSIVE_MAX:-50100}"
PROFTPD_RUNTIME_CONF="/etc/proftpd/conf.d/runtime.conf"

if [ -x /usr/local/bin/php ]; then
    APP_PHP=/usr/local/bin/php
else
    APP_PHP="${APP_PHP:-php}"
fi

read_upload_daemon_limits() {
    CONFIG_PATH="${CONFIG_PATH:-${CONFIG_FILE}}" "$APP_PHP" -r '
        $configPath = getenv("CONFIG_PATH") ?: "/var/www/html/config/airports.json";
        putenv("CONFIG_PATH=" . $configPath);
        require_once "/var/www/html/lib/config.php";
        $config = loadConfig();
        $daemon = $config["config"]["upload_daemon"] ?? $config["upload_daemon"] ?? [];
        $maxInstances = (int) ($daemon["max_instances"] ?? 50);
        $maxClients = (int) ($daemon["max_clients"] ?? 40);
        $maxPerUser = (int) ($daemon["max_clients_per_user"] ?? 2);
        if ($maxInstances < 1) { $maxInstances = 50; }
        if ($maxClients < 1) { $maxClients = 40; }
        if ($maxPerUser < 1) { $maxPerUser = 2; }
        echo $maxInstances . " " . $maxClients . " " . $maxPerUser;
    ' 2>/dev/null || echo "50 40 2"
}

write_runtime_conf() {
    local limits max_instances max_clients max_per_user
    limits="$(read_upload_daemon_limits)"
    max_instances="$(echo "$limits" | awk '{print $1}')"
    max_clients="$(echo "$limits" | awk '{print $2}')"
    max_per_user="$(echo "$limits" | awk '{print $3}')"

    mkdir -p /etc/proftpd/conf.d
    {
        echo "# Generated by configure-proftpd.sh - do not edit by hand"
        echo "Port                            ${FTP_CONTROL_PORT}"
        echo "PassivePorts                    ${FTP_PASSIVE_MIN} ${FTP_PASSIVE_MAX}"
        echo "MaxInstances                    ${max_instances}"
        echo "MaxClients                      ${max_clients}"
        echo "MaxClientsPerUser               ${max_per_user}"
        echo "Umask                           002"
    } >"$PROFTPD_RUNTIME_CONF"
    echo "✓ ProFTPD runtime: port=${FTP_CONTROL_PORT} pasv ${FTP_PASSIVE_MIN}-${FTP_PASSIVE_MAX}"
}

sync_upload_endpoint_config() {
    if [ ! -f /var/www/html/scripts/refresh-upload-endpoints.php ]; then
        echo "⚠️  Warning: refresh-upload-endpoints.php not found"
        return 1
    fi
    if CONFIG_PATH="$CONFIG_FILE" "$APP_PHP" /var/www/html/scripts/refresh-upload-endpoints.php --no-reload; then
        echo "✓ Upload endpoint cache and ProFTPD masquerade synced"
        return 0
    fi
    echo "⚠️  Warning: upload endpoint sync failed"
    return 1
}

start_proftpd_instance() {
    local pid_var="${1:-PROFTPD_PID}"
    local listen_port="${FTP_CONTROL_PORT}"

    if [ ! -f "$PROFTPD_CONF" ]; then
        echo "⚠️  Warning: ProFTPD config not found: $PROFTPD_CONF"
        return 1
    fi

    if ! proftpd -t -c "$PROFTPD_CONF" >/dev/null 2>&1; then
        echo "⚠️  Warning: ProFTPD config syntax check failed"
        proftpd -t -c "$PROFTPD_CONF" 2>&1 | head -20 || true
        return 1
    fi

    echo "Starting ProFTPD (dual-stack)..."
    proftpd -c "$PROFTPD_CONF" &
    local pid=$!
    eval "$pid_var=$pid"

    local max_iterations=6 iteration=0 process_ok=false port_ok=false
    local port_check_cmd=""
    if command -v ss >/dev/null 2>&1; then
        port_check_cmd="ss -tuln"
    elif command -v netstat >/dev/null 2>&1; then
        port_check_cmd="netstat -tuln"
    else
        port_ok=true
    fi

    while [ $iteration -lt $max_iterations ]; do
        if kill -0 "$pid" 2>/dev/null; then
            process_ok=true
            if [ -n "$port_check_cmd" ]; then
                if $port_check_cmd 2>/dev/null | grep -qE ":${listen_port}[[:space:]]|:${listen_port}\$"; then
                    port_ok=true
                    break
                fi
            fi
        else
            echo "⚠️  Warning: ProFTPD process exited during startup"
            eval "$pid_var=\"\""
            return 1
        fi
        sleep 0.5
        iteration=$((iteration + 1))
    done

    if [ "$process_ok" = true ] && [ "$port_ok" = true ]; then
        echo "✓ ProFTPD started on port ${listen_port} (PID: ${pid})"
        return 0
    fi
    if [ "$process_ok" = true ]; then
        echo "⚠️  Warning: ProFTPD running but port ${listen_port} not confirmed listening yet"
        return 0
    fi
    eval "$pid_var=\"\""
    return 1
}

configure_and_start_proftpd() {
    if [ ! -f "$PROFTPD_CONF" ]; then
        echo "⚠️  Warning: ProFTPD config not found - FTP service unavailable"
        return 1
    fi

    mkdir -p /etc/proftpd/conf.d
    touch /var/log/proftpd.log
    chmod 644 /var/log/proftpd.log

    write_runtime_conf
    sync_upload_endpoint_config || true
    start_proftpd_instance "PROFTPD_PID" || true
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    CONFIG_FILE="$CONFIG_FILE" configure_and_start_proftpd
fi
