#!/bin/bash
# Generate FTP passive port mappings for Docker Compose
# Usage: ./generate-ftp-ports.sh [min_port] [max_port]
#
# Examples:
#   ./generate-ftp-ports.sh 50000 50099  # 100 ports
#   ./generate-ftp-ports.sh 50000 50049  # 50 ports
#   ./generate-ftp-ports.sh              # Default: 50000-50099

set -euo pipefail

MIN_PORT="${1:-50000}"
MAX_PORT="${2:-50099}"

# Validate inputs
if ! [[ "$MIN_PORT" =~ ^[0-9]+$ ]] || ! [[ "$MAX_PORT" =~ ^[0-9]+$ ]]; then
    echo "ERROR: Ports must be numeric" >&2
    exit 1
fi

if [ "$MIN_PORT" -lt 1024 ] || [ "$MAX_PORT" -gt 65535 ]; then
    echo "ERROR: Ports must be between 1024 and 65535" >&2
    exit 1
fi

if [ "$MIN_PORT" -ge "$MAX_PORT" ]; then
    echo "ERROR: min_port must be less than max_port" >&2
    exit 1
fi

PORT_COUNT=$((MAX_PORT - MIN_PORT + 1))

echo "# FTP passive mode ports ($MIN_PORT-$MAX_PORT) - $PORT_COUNT ports"
echo "# Generated by scripts/generate-ftp-ports.sh"
echo "#"

for port in $(seq "$MIN_PORT" "$MAX_PORT"); do
    echo "      - \"$port:$port\"  # FTP passive mode"
done

echo ""
echo "# Total: $PORT_COUNT ports for passive FTP connections"

