name: Deploy to Bluehost

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md'
      - '.gitignore'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    
    - name: Run tests first
      run: |
        php -l index.php
        php -l airport-template.php
        php -l weather.php
        php -l webcam.php
        php -l homepage.php
    
    - name: Create deployment package
      run: |
        echo "Creating deployment package..."
        
        # Create directories for Bluehost
        mkdir -p deploy/cache/webcams
        mkdir -p deploy/cache
        
        # Copy files (exclude development files)
        cp -r *.php deploy/
        cp -r *.css deploy/
        cp airports.json.example deploy/
        cp README.md deploy/
        cp CONFIGURATION.md deploy/
        cp SECURITY.md deploy/
        cp SETUP.md deploy/
        cp .htaccess deploy/ 2>/dev/null || true
        
        # Create .htaccess if it doesn't exist
        if [ ! -f deploy/.htaccess ]; then
          cat > deploy/.htaccess <<'EOF'
# AviationWX URL Rewriting
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteBase /
  
  # Force HTTPS
  RewriteCond %{HTTPS} off
  RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
  
  # Default to index.php for routing
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule ^(.*)$ index.php [QSA,L]
</IfModule>

# Security
<FilesMatch "^(airports\.json|\.git|\.gitignore)">
  Order allow,deny
  Deny from all
</FilesMatch>

# Cache webcam images
<FilesMatch "\.jpg$">
  ExpiresActive On
  ExpiresDefault "access plus 1 minute"
</FilesMatch>
EOF
        fi
        
        # Make cache directories writable
        chmod 755 deploy/cache
        chmod 755 deploy/cache/webcams
        
        echo "✓ Deployment package created"
        ls -la deploy/
    
    - name: Deploy to Bluehost via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.BLUEHOST_FTP_HOST }}
        username: ${{ secrets.BLUEHOST_FTP_USER }}
        password: ${{ secrets.BLUEHOST_FTP_PASSWORD }}
        local-dir: ./deploy/
        server-dir: /public_html/
        dangerous-clean-slate: false
        exclude: |
          **/.git*
          **/.git*/**
          airports.json
          **/*.md
          **/cache/**
    
    - name: Post-deployment verification
      run: |
        echo "Verifying deployment..."
        sleep 5
        # Check if site is accessible
        curl -f https://aviationwx.org/ || echo "Warning: Site might not be immediately available"

