name: Deploy to Droplet (Docker)

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**.md"
      - "**.MD"
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Only runs on push to main or manual dispatch per triggers above
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Sync repository to server
        run: |
          rsync -az --delete --exclude '.git' ./ ${{ secrets.USER }}@${{ secrets.HOST }}:~/aviationwx/

      - name: Deploy via Docker Compose
        run: |
          ssh ${{ secrets.USER }}@${{ secrets.HOST }} << 'EOF'
          set -euo pipefail
          cd ~/aviationwx
          docker compose -f docker-compose.prod.yml up -d --build
          docker system prune -f
          EOF

