name: Deploy to Bluehost

on:
  workflow_run:
    workflows: ["Test AviationWX"]
    types:
      - completed
    branches: [ main ]
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md'
      - '.gitignore'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # Only deploy if tests passed
    if: github.event_name == 'push' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    
    - name: Create deployment package
      run: |
        echo "Creating deployment package..."
        
        # Create directories for Bluehost
        mkdir -p deploy/cache/webcams
        mkdir -p deploy/cache
        
        # Copy files (exclude development files)
        cp -r *.php deploy/
        cp -r *.css deploy/
        cp airports.json.example deploy/
        cp README.md deploy/
        cp CONFIGURATION.md deploy/
        cp SECURITY.md deploy/
        cp SETUP.md deploy/
        # Copy .htaccess
        if [ -f .htaccess ]; then
          cp .htaccess deploy/
          echo "✓ Copied .htaccess"
        else
          echo "⚠️  No .htaccess found in repo"
        fi
        
        # Make cache directories writable
        chmod 755 deploy/cache
        chmod 755 deploy/cache/webcams
        
        echo "✓ Deployment package created"
        ls -la deploy/
    
    - name: Deploy to Bluehost via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.BLUEHOST_FTP_HOST }}
        username: ${{ secrets.BLUEHOST_FTP_USER }}
        password: ${{ secrets.BLUEHOST_FTP_PASSWORD }}
        local-dir: ./deploy/
        server-dir: /
        dangerous-clean-slate: false
        exclude: |
          **/.git*
          **/.git*/**
          airports.json
          **/*.md
          **/cache/**
    
    - name: Post-deployment verification
      run: |
        echo "Verifying deployment..."
        sleep 5
        # Check if site is accessible
        curl -f https://aviationwx.org/ || echo "Warning: Site might not be immediately available"

