name: Non-Blocking Tests

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch: {} # Allow manual trigger

jobs:
  performance-tests:
    name: Performance Tests (Non-Blocking)
    runs-on: ubuntu-latest
    continue-on-error: true  # Don't block PR if these fail
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: apcu, gd, zip, curl, json, mbstring
          coverage: none
      
      - name: Install Composer dependencies
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader --no-progress
      
      - name: Run Performance Tests
        run: |
          echo "Running performance tests..."
          vendor/bin/phpunit --testsuite Performance --testdox --log-junit performance-results.xml || [ $? -eq 1 ]
        continue-on-error: true
        env:
          CONFIG_PATH: tests/Fixtures/airports.json.test
      
      - name: Upload Performance Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: performance-test-results
          path: performance-results.xml
          retention-days: 7
  
  e2e-tests:
    name: End-to-End Tests (Non-Blocking)
    runs-on: ubuntu-latest
    continue-on-error: true  # Don't block PR if these fail
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: apcu, gd, zip, curl, json, mbstring
          coverage: none
      
      - name: Install Composer dependencies
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader --no-progress
      
      - name: Create test airports.json
        run: |
          # Create airports.json from example for Docker
          if [ ! -f airports.json ]; then
            cp airports.json.example airports.json
            echo "✓ Created airports.json from example"
          fi
      
      - name: Start Docker containers
        run: |
          # Start local instance for testing
          docker compose up -d
          sleep 15  # Wait for containers to be ready
          docker compose ps
      
      - name: Wait for health check
        run: |
          timeout=60
          elapsed=0
          while [ $elapsed -lt $timeout ]; do
            if curl -f http://localhost:8080/health.php 2>/dev/null || curl -f http://localhost:8080/ 2>/dev/null; then
              echo "✓ Service is ready"
              exit 0
            fi
            sleep 2
            elapsed=$((elapsed + 2))
            echo "Waiting for service... ${elapsed}s"
          done
          echo "⚠ Service did not become ready in time"
          docker compose logs web
      
      - name: Run E2E Tests
        run: |
          echo "Running E2E tests with mocked APIs..."
          echo "Note: These tests use mocked API responses"
          vendor/bin/phpunit --testsuite E2E --testdox --log-junit e2e-results.xml || [ $? -eq 1 ]
        continue-on-error: true
        env:
          TEST_API_URL: http://localhost:8080
      
      - name: Cleanup
        if: always()
        run: |
          docker compose down
      
      - name: Upload E2E Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results
          path: e2e-results.xml
          retention-days: 7
  
  smoke-tests:
    name: Smoke Tests - Local (Non-Blocking)
    runs-on: ubuntu-latest
    continue-on-error: true  # Don't block PR if these fail
    if: github.event_name == 'pull_request' || github.event_name == 'push'  # Auto on PRs and pushes
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: apcu, gd, zip, curl, json, mbstring
          coverage: none
      
      - name: Install Composer dependencies
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader --no-progress
      
      - name: Create test airports.json
        run: |
          # Create airports.json from example for Docker
          if [ ! -f airports.json ]; then
            cp airports.json.example airports.json
            echo "✓ Created airports.json from example"
          fi
      
      - name: Start Docker containers
        run: |
          docker compose up -d
          sleep 15
      
      - name: Run Smoke Tests (Local)
        run: |
          echo "Running smoke tests against local instance..."
          echo "Note: Docker container uses airports.json (mounted from host)"
          vendor/bin/phpunit --testsuite Smoke --testdox --log-junit smoke-results.xml || [ $? -eq 1 ]
        continue-on-error: true
        env:
          TEST_API_URL: http://localhost:8080
          # Note: CONFIG_PATH not set here - Docker container should use /var/www/html/airports.json
      
      - name: Cleanup
        if: always()
        run: |
          docker compose down
      
      - name: Upload Smoke Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-test-results
          path: smoke-results.xml
          retention-days: 7
  
  smoke-tests-production:
    name: Smoke Tests - Production (Manual Only)
    runs-on: ubuntu-latest
    continue-on-error: true
    if: github.event_name == 'workflow_dispatch'  # Only manual dispatch
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: apcu, gd, zip, curl, json, mbstring
          coverage: none
      
      - name: Install Composer dependencies
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader --no-progress
      
      - name: Run Smoke Tests (Production)
        run: |
          echo "⚠️  WARNING: Running smoke tests against PRODUCTION"
          echo "Production URL: https://aviationwx.org"
          # Allow warnings but fail on actual test failures
          vendor/bin/phpunit --testsuite Smoke --testdox --log-junit smoke-prod-results.xml || [ $? -eq 1 ]
        continue-on-error: true
        env:
          TEST_PROD_URL: https://aviationwx.org
      
      - name: Upload Production Smoke Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-prod-test-results
          path: smoke-prod-results.xml
          retention-days: 7
  
  browser-tests:
    name: Browser Compatibility Tests (Non-Blocking)
    runs-on: ubuntu-latest
    continue-on-error: true  # Don't block PR if these fail
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: tests/Browser/package.json
      
      - name: Install Playwright dependencies
        working-directory: tests/Browser
        run: |
          npm install
          # Install browsers we test in CI (Chromium, Firefox, WebKit for desktop + mobile)
          npx playwright install --with-deps chromium firefox webkit
      
      - name: Create test airports.json
        run: |
          # Create airports.json from example for Docker
          if [ ! -f airports.json ]; then
            cp airports.json.example airports.json
            echo "✓ Created airports.json from example"
          fi
      
      - name: Start Docker containers
        run: |
          docker compose up -d
          sleep 15
          docker compose ps
      
      - name: Wait for service to be ready
        run: |
          timeout=60
          elapsed=0
          while [ $elapsed -lt $timeout ]; do
            if curl -f http://localhost:8080/ 2>/dev/null; then
              echo "✓ Service is ready"
              exit 0
            fi
            sleep 2
            elapsed=$((elapsed + 2))
          done
          echo "⚠ Service did not become ready"
          docker compose logs web
      
      - name: Run Browser Tests
        working-directory: tests/Browser
        run: |
          # Run browser tests - exit code handling for Playwright
          npx playwright test || [ $? -eq 1 ]
        continue-on-error: true
        env:
          TEST_BASE_URL: http://localhost:8080
      
      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: tests/Browser/playwright-report/
          retention-days: 7
      
      - name: Upload Playwright Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: tests/Browser/playwright-results.json
          retention-days: 7
      
      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-screenshots
          path: tests/Browser/test-results/
          retention-days: 7
      
      - name: Cleanup
        if: always()
        run: |
          docker compose down
  
  test-results-summary:
    name: Test Results Summary
    runs-on: ubuntu-latest
    needs: [performance-tests, e2e-tests, smoke-tests, browser-tests]
    if: always()
    permissions:
      pull-requests: write
      contents: read
      issues: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Download all test results
        uses: actions/download-artifact@v4
        with:
          pattern: '*-test-results*'
          merge-multiple: true
          path: test-results
      
      - name: Download browser screenshots
        uses: actions/download-artifact@v4
        with:
          pattern: 'playwright-screenshots'
          path: test-results/browser-screenshots
          if-no-files-found: ignore
      
      - name: Generate Test Summary
        run: |
          echo "## Test Results Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Performance Tests" >> $GITHUB_STEP_SUMMARY
          if [ -f test-results/performance-results.xml ]; then
            echo "✓ Results available" >> $GITHUB_STEP_SUMMARY
          else
            echo "⚠ No results found" >> $GITHUB_STEP_SUMMARY
          fi
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### E2E Tests" >> $GITHUB_STEP_SUMMARY
          if [ -f test-results/e2e-results.xml ]; then
            echo "✓ Results available" >> $GITHUB_STEP_SUMMARY
          else
            echo "⚠ No results found" >> $GITHUB_STEP_SUMMARY
          fi
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Smoke Tests" >> $GITHUB_STEP_SUMMARY
          if [ -f test-results/smoke-results.xml ]; then
            echo "✓ Results available" >> $GITHUB_STEP_SUMMARY
          else
            echo "⚠ No results found" >> $GITHUB_STEP_SUMMARY
          fi
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Browser Tests" >> $GITHUB_STEP_SUMMARY
          if [ -f test-results/playwright-results.json ]; then
            echo "✓ Results available" >> $GITHUB_STEP_SUMMARY
          else
            echo "⚠ No results found" >> $GITHUB_STEP_SUMMARY
          fi
      
      - name: Comment PR with Results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            // Check which tests passed/failed
            const results = {
              performance: 'unknown',
              e2e: 'unknown',
              smoke: 'unknown',
              browser: 'unknown'
            };
            
            try {
              if (fs.existsSync('test-results/performance-results.xml')) {
                const content = fs.readFileSync('test-results/performance-results.xml', 'utf8');
                results.performance = content.includes('failures="0"') ? 'passed' : 'failed';
              }
            } catch (e) {}
            
            try {
              if (fs.existsSync('test-results/e2e-results.xml')) {
                const content = fs.readFileSync('test-results/e2e-results.xml', 'utf8');
                results.e2e = content.includes('failures="0"') ? 'passed' : 'failed';
              }
            } catch (e) {}
            
            try {
              if (fs.existsSync('test-results/smoke-results.xml')) {
                const content = fs.readFileSync('test-results/smoke-results.xml', 'utf8');
                results.smoke = content.includes('failures="0"') ? 'passed' : 'failed';
              }
            } catch (e) {}
            
            // Parse Playwright JSON results for browser tests
            try {
              if (fs.existsSync('test-results/playwright-results.json')) {
                const playwrightData = JSON.parse(fs.readFileSync('test-results/playwright-results.json', 'utf8'));
                const totalTests = playwrightData.stats?.total || 0;
                const failedTests = playwrightData.stats?.failures || 0;
                const skippedTests = playwrightData.stats?.skipped || 0;
                if (totalTests > 0 && failedTests === 0) {
                  results.browser = skippedTests > 0 ? 'passed-with-skipped' : 'passed';
                } else if (failedTests > 0) {
                  results.browser = 'failed';
                } else {
                  results.browser = 'unknown';
                }
              }
            } catch (e) {
              console.log('Error parsing Playwright results:', e.message);
            }
            
            // Find representative screenshots (mobile and desktop)
            let mobileScreenshot = null;
            let desktopScreenshot = null;
            const screenshotsDir = 'test-results/browser-screenshots/playwright-screenshots';
            
            // Helper function to recursively find screenshots
            const findScreenshots = (dir) => {
              try {
                if (!fs.existsSync(dir)) return;
                const entries = fs.readdirSync(dir, { withFileTypes: true });
                for (const entry of entries) {
                  const fullPath = path.join(dir, entry.name);
                  if (entry.isDirectory()) {
                    findScreenshots(fullPath);
                  } else if (entry.isFile() && entry.name.includes('screenshot') && entry.name.endsWith('.png')) {
                    // Check for mobile screenshot (Mobile Chrome or contains 'mobile')
                    if ((entry.name.includes('mobile') || entry.name.includes('Mobile')) && !mobileScreenshot) {
                      mobileScreenshot = fullPath;
                    } 
                    // Check for desktop screenshot (chromium, desktop, or not mobile/tablet)
                    else if ((entry.name.includes('chromium') || entry.name.includes('desktop') || 
                             (!entry.name.includes('mobile') && !entry.name.includes('tablet') && !entry.name.includes('Tablet'))) && !desktopScreenshot) {
                      desktopScreenshot = fullPath;
                    }
                  }
                }
              } catch (e) {
                console.log('Error scanning directory:', dir, e.message);
              }
            };
            
            findScreenshots(screenshotsDir);
            
            // Build screenshot section - reference artifacts since GitHub doesn't support base64 in PR comments
            let screenshotSection = '';
            if (mobileScreenshot || desktopScreenshot) {
              screenshotSection = '\n\n## 📸 Visual Test Results\n\n';
              screenshotSection += 'Screenshots from browser compatibility tests:\n\n';
              if (mobileScreenshot) {
                screenshotSection += `- **Mobile View**: Screenshot available in [workflow artifacts](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})\n`;
              }
              if (desktopScreenshot) {
                screenshotSection += `- **Desktop View**: Screenshot available in [workflow artifacts](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})\n`;
              }
              screenshotSection += '\n> 💡 **Tip**: Download the `playwright-screenshots` artifact from the workflow run to view full-size screenshots.\n';
            }
            
            const comment = `## 📊 Non-Blocking Test Results
            
            These tests provide quality assurance but do **not block PR merges**.
            
            | Test Suite | Status |
            |------------|--------|
            | Performance Tests | ${results.performance === 'passed' ? '✅ Passed' : results.performance === 'failed' ? '⚠️ Failed' : '⏭️ Skipped'} |
            | E2E Tests | ${results.e2e === 'passed' ? '✅ Passed' : results.e2e === 'failed' ? '⚠️ Failed' : '⏭️ Skipped'} |
            | Smoke Tests | ${results.smoke === 'passed' ? '✅ Passed' : results.smoke === 'failed' ? '⚠️ Failed' : '⏭️ Skipped'} |
            | Browser Tests | ${results.browser === 'passed' || results.browser === 'passed-with-skipped' ? '✅ Passed' : results.browser === 'failed' ? '⚠️ Failed' : '⏭️ Skipped'} |
            ${screenshotSection}
            📦 **Test artifacts** are available in the workflow run artifacts section.
            
            💡 **Note:** These tests are non-blocking. Review failures but they won't prevent merge.`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
